contact/urls.py
from django.urls import path

from contact import views

app_name = 'contact'

urlpatterns = [
    path('contact/<int:contact_id>/detail/', views.contact, name='contact'),  # type:ignore
   
    path('search/', views.search, name='search'), # type:ignore 
    path('', views.index, name='index'),  # type:ignore

   #### contact (Create)CRUD ####

     path('contact/create/', views.create, name='create'),  # type:ignore
     path('contact/<int:contact_id>/update/', views.update, name='update'),
     path('contact/<int:contact_id>/delete/', views.delete, name='delete'),

   ### crud 

    path('user/create/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/logout/', views.logout_view, name='logout'),
    path('user/update/', views.user_update, name='user_update'),
      
      

]  

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('contact.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

contact/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

# id (primary key - automático)
# first_name (string), last_name (string), phone (string)
# email (email), created_date (date), description (text)
# category (foreign key), show (boolean), picture (imagem)
# owner (foreign key)


class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.name


class Contact(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField(max_length=254, blank=True)
    created_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)
    show = models.BooleanField(default=True)
    picture = models.ImageField(blank=True, upload_to='pictures/%Y/%m/')
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        blank=True, null=True
    )
    owner = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        blank=True, null=True
    )

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

contact/forms.py
from django import forms # import modulo de formulario 
from django.core.exceptions import ValidationError ## validação de erros 
from . import models


from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import password_validation


class ContactForm(forms.ModelForm):
    
    picture = forms.ImageField(
        widget=forms.FileInput(
            attrs={
                'class': 'classe-a classe-b',
                'placeholder': 'Aqui veio do init',
                'accept': 'image/*',
            }
        
    
      
        )
        
    )



    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
        
    #     self.fields['first_name'].widget.attrs.update({
    #         'class': 'class-a class-b',
    #         'placeholder': 'Escreva aqui',
    #     })



    ###incluir os campos do formulario
    class Meta:
        model = models.Contact
        fields = (
            'first_name', 'last_name', 'phone',
            'email', 'description', 'category',
            'picture',
        )
    def clean(self):
        cleaned_data = self.cleaned_data
        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')

        if first_name == last_name:
            msg = ValidationError(
                'Primeiro nome não pode ser igual ao segundo',
                code='invalid'
            )
            self.add_error('first_name', msg)
            self.add_error('last_name', msg)

        return super().clean()

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')

        if first_name == 'ABC':
            self.add_error(
                'first_name',
                ValidationError(
                    'Veio do add_error',
                    code='invalid'
                )
            )
        print(first_name)
        return first_name
    
class RegisterForm(UserCreationForm):
    ...
    first_name = forms.CharField(
        required=True,
        min_length=3,
    )
    last_name = forms.CharField(
        required=True,
        min_length=3,
    )
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError('Já existe este e-mail', code='invalid')
            )

        return email
    


class RegisterUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={
            'min_length': 'Please, add more than 2 letters.'
        }
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.'
    )

    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label="Password 2",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Use the same password as before.',
        required=False,
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username',
        )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)

        if commit:
            user.save()

        return user

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Senhas não batem')
                )

        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('Já existe este e-mail', code='invalid')
                )

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                )

        return password1

contact/views/contact_forms.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from contact.forms import ContactForm
from contact.models import Contact


@login_required(login_url='contact:login')
def create(request):
    form_action = reverse('contact:create')

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save(commit=False)
            contact.owner = request.user
            contact.save()
            return redirect('contact:update', contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        'form': ContactForm(),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
    )


@login_required(login_url='contact:login')
def update(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True, owner=request.user
    )
    form_action = reverse('contact:update', args=(contact_id,))

    if request.method == 'POST':
        form = ContactForm(request.POST, request.FILES, instance=contact)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            contact = form.save()
            return redirect('contact:update', contact_id=contact.pk)

        return render(
            request,
            'contact/create.html',
            context
        )

    context = {
        'form': ContactForm(instance=contact),
        'form_action': form_action,
    }

    return render(
        request,
        'contact/create.html',
        context
    )


@login_required(login_url='contact:login')
def delete(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, show=True, owner=request.user
    )
    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('contact:index')

    return render(
        request,
        'contact/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation,
        }
    )

contact/views/contact_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render

from contact.models import Contact


def index(request):
    contacts = Contact.objects \
        .filter(show=True)\
        .order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Contatos - '
    }

    return render(
        request,
        'contact/index.html',
        context
    )


def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('contact:index')

    contacts = Contact.objects \
        .filter(show=True)\
        .filter(
            Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value) |
            Q(phone__icontains=search_value) |
            Q(email__icontains=search_value)
        )\
        .order_by('-id')

    paginator = Paginator(contacts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Search - ',
        'search_value': search_value,
    }

    return render(
        request,
        'contact/index.html',
        context
    )


def contact(request, contact_id):
    # single_contact = Contact.objects.filter(pk=contact_id).first()
    single_contact = get_object_or_404(
        Contact, pk=contact_id, show=True
    )
    site_title = f'{single_contact.first_name} {single_contact.last_name} - '

    context = {
        'contact': single_contact,
        'site_title': site_title
    }

    return render(
        request,
        'contact/contact.html',
        context
    )

contact/views/user_forms.py
from django.contrib import  messages, auth
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm

from django.contrib.auth.decorators import login_required

from contact.forms import RegisterForm, RegisterUpdateForm


def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Usuário registrado')
            return redirect('contact:login')

    return render(
        request,
        'contact/register.html',
        {
            'form': form
        }
    )
    

def login_view(request):
       
      form = AuthenticationForm(request)

      if request.method == 'POST':
       form = AuthenticationForm(request, data=request.POST)
 
      if form.is_valid():
           user = form.get_user()
           auth.login(request, user)
           messages.success(request, 'Logado')
           return redirect('contact:index')

      else:
          messages.error(request, 'Login invalido')
      

      return render(
        request,
        'contact/login.html',
        {
            'form': form 
        }
    )


@login_required(login_url='contact:login')
def logout_view(request):
    auth.logout(request)
    return redirect('contact:login')



@login_required(login_url='contact:login')
def user_update(request):
    form = RegisterUpdateForm(instance=request.user)

    if request.method != 'POST':
        return render(
            request,
            'contact/user_update.html',
            {
                'form': form
            }
        )

    form = RegisterUpdateForm(data=request.POST, instance=request.user)

    if not form.is_valid():
        return render(
            request,
            'contact/user_update.html',
            {
                'form': form
            }
        )

    form.save()
    auth.login(request, request.user) 
    messages.success(request, "Atualizado com sucesso.")
    return redirect("contact:user_update")

contact/templates/contact/contact.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="single-contact">
    <h1 class="single-contact-name">
      {{ contact.first_name }} {{ contact.last_name }}
    </h1>

    <p><b>ID:</b> {{ contact.id }}</p>
    <p><b>E-mail:</b> {{ contact.email }}</p>
    <p><b>Phone:</b> {{ contact.phone }}</p>
    <p><b>Created Date:</b> {{ contact.created_date }}</p>
    <p><b>Description:</b> {{ contact.description }}</p>
    <p><b>Category:</b> {{ contact.category.name }}</p>

    {% if contact.picture %}
      <p>
        <img src="{{ contact.picture.url }}" alt="{{ contact.first_name }} {{ contact.last_name }}">
      </p>
    {% endif %}
      
    {% if user == contact.owner %}
    <div class="contact-links">
      <a class="btn btn-link" href="{% url 'contact:update' contact.id %}">Update</a>
      <form action="{% url 'contact:delete' contact.id %}" method="POST">
        {% csrf_token %}
        {% if confirmation == 'no' %}
          <input type="hidden" name="confirmation" value="yes">
          <button class="btn btn-link btn-delete" type="submit">Confirma?</button>
        {% else %}
          <button class="btn btn-link btn-delete" type="submit">Delete</button>
        {% endif %}
      </form>
    </div>

    {% endif %}
  </div>
{% endblock content %}

contact/templates/contact/create.html
{% extends 'global/base.html' %}

{% block content %}
  <h1>CREATE CONTACT</h1>
  <div class="form-wrapper">
    <h2>Contact</h2>
    
    <form 
      action="{{ form_action }}"
      method="POST"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      {% comment %} pegando o label do form {% endcomment %}
      {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {{ field.errors }}
          {% if field.help_text %}
            <p class="help-text">{{ field.help_text }}</p>
          {% endif %}
        </div>

        {% if field.name == 'picture' and field.value %}
          <div class="form-group">
            <img src="{{ field.value.url }}" alt="">
          </div>
        {% endif %}
      {% endfor %}

      {% if form.non_field_errors %}
        <div class="form-content">
          <div class="form-group">
            <div class="message error">
              {{ form.non_field_errors }}
            </div>
          </div>
        </div>
      {% endif %}

      <div class="form-content">
        <div class="form-group">
          <button class="btn" type="submit">Send</button>
        </div>
      </div>
    </form>
  </div> 

{% endblock content %}

contact/templates/contact/index.html
{% extends 'global/base.html' %}

{% block content %}
  {% if page_obj %}
    <div class="responsive-table">
      <table class="contacts-table">
        <caption class="table-caption ">
          Contacts
        </caption>

        <thead>
          <tr class="table-row table-row-header">
            <th class="table-header">ID</th>
            <th class="table-header">First Name</th>
            <th class="table-header">Last Name</th>
            <th class="table-header">Phone</th>
            <th class="table-header">E-mail</th>
          </tr>
        </thead>

        <tbody>
          {% for contact in page_obj %}
            <tr class="table-row">
              <td class="table-cel">
                <a 
                  class="table-link" 
                  href="{% url 'contact:contact' contact.id %}"
                >
                  {{ contact.id }}
                </a>
              </td>
              <td class="table-cel">
                {{ contact.first_name }}
              </td>
              <td class="table-cel">
                {{ contact.last_name }}
              </td>
              <td class="table-cel">
                {{ contact.phone }}
              </td>
              <td class="table-cel">
                {{ contact.email }}
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% else %}
    <div class="single-contact">
      <h1 class="single-contact-name">
        Nenhum contato encontrado.
      </h1>
    </div>
  {% endif %}
{% endblock content %}

contact/templates/contact/login.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Login </h2>

    {% if user.is_authenticated %}
      <p>
        Você fez login como {{ user.username }}.
        Clique <a href="{% url 'contact:logout' %}">aqui</a>
        para sair.
      </p>
    {% else %}
      {% include 'contact/partials/_user-form.html' %}
    {% endif %}
  </div>
{% endblock content %}

contact/templates/contact/register.html
{% extends 'global/base.html' %}
{% block content %}
  <div class="form-wrapper">
    <h2>Register</h2>
      {% include "contact/partials/_user-form.html" %}
  </div>
{% endblock content %}

contact/templates/contact/user_update.html
{% extends 'global/base.html' %}

{% block content %}
  <div class="form-wrapper">

    <h2>Update User</h2>

    {% include 'contact/partials/_user-form.html' %}
  </div>
{% endblock content %}